adding new fields and relationships
jhipster/jdl-samples pull request #19
Opened 2020-02-04 16:53 UTC by amatosg

2020-02-06 13:42 UTC, atomfrede requested changes
Besides the small typo it looks good to me.

2020-02-06 13:42 UTC, atomfrede commented on bug-tracker.jh
> +  HI("Hi")
I think it should be `HIGH("HIGH")`

```suggestion
HIGH("HIGH")
```

2020-02-06 14:47 UTC, amatosg commented on bug-tracker.jh
> +  HI("Hi")
thanks! typo fixed

2020-03-25 04:57 UTC, amatosg commented
@atomfrede can this be merged now?

2020-03-25 07:39 UTC, atomfrede approved these changes

2020-03-25 07:40 UTC, atomfrede commented
@amatosg Sorry, totally forgot about this. Let's merge it. Thanks!

2020-03-25 07:40 UTC, merged